---
- name: Deploy n8n with Docker Compose
  hosts: n8n
  become: true # Run with sudo privileges

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: true
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Create n8n data directory
      ansible.builtin.file:
        path: /opt/n8n/data
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/docker-compose.yml"
        dest: /opt/n8n/docker-compose.yml

    - name: Start n8n containers
      community.docker.docker_compose_v2:
        project_src: /opt/n8n
        state: present
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output