---
# file: playbook.yaml
- name: Install n8n on Ubuntu
  hosts: all
  become: yes  # Use sudo to install packages
  tasks:
    - name: Node.js install script from NodeSource PPA (personal package archive) 
      shell:
        cmd: curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    - name: Update nodejs
      apt:
        update_cache: yes
        pkg:
          - nodejs
          - npm
    
    - name: Install n8n via npm
      shell:
        cmd: npm install -g n8n pm2

    - name: Run n8n
      shell:
        cmd: pm2 start n8n

    - name: Run n8n on reboot
      shell:
        cmd: pm2 startup

    - name: Save current PM2 process list
      shell:
        cmd: pm2 save